site_name: testing Github Page
index_pages:
  - new page: wiki/DO180-apps/Home.md

nav:
  - Home: index.md
  - Another Page: another-page.md
  - New Page: new-page.md

pages:
  - Home: index.md
  - Another Page: another-page.md
  - New Page: new-page.md


# Repository
repo_name: nharshav/DO180-apps
repo_url: https://github.com/nharshav/DO180-apps

# Copyright


# Configuration
theme:
  name: material
  # logo : logo.png

  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.footnote.tooltips
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.preview
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    #- navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  font:
    text: Roboto
    code: Roboto Mono
  favicon: logo.png
  icon:
    logo: logo

# Plugins
plugins:
  - blog
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  



# Additional configuration
extra:
  status:
    new: Recently added
    deprecated: Deprecated
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  social:
    - icon: fontawesome/brands/github
      link: https://github.boschdevcloud.com/bios-robotics/bosch_buildfarm_provisioning
   # - icon: fontawesome/brands/docker
   # - icon: fontawesome/brands/python   
  #  - icon: fontawesome/brands/mastodon
 #   - icon: fontawesome/brands/twitter
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark 

  - toc:
      permalink: true
      permalink_class: "mk-toc-permalink"
      toc_depth: 3  # Adjust the depth as needed
      #toc_locked: true  # Lock the TOC when scrolling
      #toc_float: left  # Place the TOC on the left side
